### ISSUE TITLE
XML and JSON schemas

### ISSUE THREAD

**Issue by aethelwulffe** [CMSgov/qpp-submissions-docs#26]
I would add a "question" label here, but it appears that this repo is not supporting labels.
Where, in this repo or another, is the actual XML and JSON schema for reporting the MIPS QA measures (specifically or inclusive of the Registry variety of the same)?  Preferably compliant with w3.org/XML/Schema and/or json-schema.org.
  If this does not exist, I would love to participate in such a project, as well as contributing web-standard type content for tools that parse x12 and ccrl file data to calculate said measures (which already exists).
  There is a great need out there for not only a clean set of standards for the XML and JSON formats (and NOT in a messy PDF) but also for full real-world examples of output drawn from a real-world data set showing end-to-end implementation.  Such an example and an open platform will allow many people to participate in the improvement process (something we also call "Quality Assurance") for these tools that are attempting to ensure the quality of other things.
Ironic...I know.

**Comment by marimiyachi** [comment]
Hi @aethelwulffe! Thanks so much for reaching out. In response to your request, we've put together [this repository](https://github.com/CMSgov/qpp-submissions-schema) which contains both JSON and XML schemas. Does this help?

I agree with you that a real-world example would be incredibly useful!

**Comment by aethelwulffe** [comment]
Hi @marimiyachi 
I am moving my issue over to that repo.  I see you have been at that project for a couple of days, and I should have been checking for new repos.  See you there.

**Comment by aethelwulffe** [comment]
https://github.com/CMSgov/qpp-submissions-schema/issues/3
